name: LuaRocks Release
on:
  release:
    types: [published]
  workflow_dispatch:
permissions:
  contents: read
  pull-requests: read

jobs:
  luarocks-release:
    if: (
      ( github.event_name == 'release' && startsWith(github.event.release.name, 'v')) ||
      github.event_name == 'workflow_dispatch'
      )
    runs-on: ubuntu-latest
    name: LuaRocks upload
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install Lux
        uses: lumen-oss/gh-actions-lux@v1
        with:
          version: 0.25.2

      # https://github.com/nvim-neorocks/lux/blob/bfce60e17740dae19032f89b8cdd1136d5b67ff0/.github/workflows/cd-luarocks.yml#L33-L37
      - name: Upload
        run: |
          lx --lua-version 5.1 upload
        env:
          LUX_API_KEY: ${{ secrets.LUAROCKS_API_KEY }}
